tools:
  zap: "/opt/zaproxy/zap.sh"
  nikto: "/usr/bin/nikto"
  testssl: "/opt/testssl.sh/testssl.sh"
  openssl: "/usr/bin/openssl"
  curl: "/usr/bin/curl"
  lynis: "/usr/sbin/lynis"
  trivy: "/usr/local/bin/trivy"
  newman: "/usr/local/bin/newman"
  python3: "/usr/bin/python3"
